# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License.AGPL.txt in the project root for license information.

packages:
  - name: docker
    type: docker
    argdeps:
      - imageRepoBase
      - gitpodWebImageDigest
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.gitpodWebImage
      buildArgs:
        IMAGE_DIGEST: ${gitpodWebImageDigest}
      image:
        - ${imageRepoBase}/ide/gitpod-web:commit-${__git_commit}
