name: "Preview environment regression check"
on:
    workflow_dispatch:
        inputs:
            name:
                required: true
                description: "The name of the preview environment"
            version:
                required: true
                description: "The version of Gitpod to install"
jobs:
    check:
        name: Check for regressions
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v3
            - name: Create preview environment infrastructure
              env:
                  TF_VAR_infra_provider: harvester
              uses: ./.github/actions/preview-create
              with:
                  name: ${{ github.event.inputs.name }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}
            - name: Deploy Gitpod to the preview environment
              id: deploy-gitpod
              uses: ./.github/actions/deploy-gitpod
              with:
                  name: ${{ github.event.inputs.name }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}
                  version: ${{ github.event.inputs.name.version}}
            - name: Check
              run: |
                  echo "No regressions caught because I didn't check anything 🤡 Sleeping for 2 minutes."
                  sleep 60
            - name: Delete preview environment
              if: always()
              uses: ./.github/actions/delete-preview
              with:
                  name: ${{ github.event.inputs.name }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}
